### ISSUE TITLE
Chromium Errors on Startup

### ISSUE THREAD

**Issue by ylluminarious** [chill117/proxy-lists#136]
I ran:

```
$ proxy-lists getProxies --countries="us" --output-format="txt"
```

And got the following errors:

```
(node:77245) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Page.js:158:24)
    at CDPSession.Page.client.on.event (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Page.js:134:56)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Connection.js:232:12)
    at Connection._onMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Connection.js:119:19)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/receiver.js:346:17)
(node:77245) Unhan(node:77245) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Page.js:158:24)
    at CDPSession.Page.client.on.event (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Page.js:134:56)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Connection.js:232:12)
    at Connection._onMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Connection.js:119:19)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/receiver.js:346:17)
(node:77245) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Page.js:158:24)
    at CDPSession.Page.client.on.event (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Page.js:134:56)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Connection.js:232:12)
    at Connection._onMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/puppeteer/lib/Connection.js:119:19)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/local/lib/node_modules/proxy-lists/node_modules/ws/lib/receiver.js:346:17)
```

It appears that it's the same error repeating itself. It only stopped when I typed `Ctrl+C`. I believe this has something to do with Chromium crashing although I'm not sure why.

System information:
- `macOS 10.15.7`
- `node v10.16.3`
  - also using `node` via `nvm 0.35.3`
- `proxy-lists 1.15.3`, installed via `npm install -g proxy-lists`

As a workaround, https://pzzqz.com/ seems to be working as an alternative for this tool. [Several](https://github.com/chill117/proxy-lists/issues/127#issuecomment-803705400) [PR's](https://github.com/chill117/proxy-lists/issues/132) have already mentioned integrating it, although that wouldn't help resolve the error which is occurring at startup.

**Comment by jwdeaa** [comment]
@ylluminarious 

you also can use pzzqz.com api to get free proxy list.

help doc:
https://pzzqz.com/settings/profile

<img width="645" alt="image" src="https://user-images.githubusercontent.com/78612272/194735677-eb34f4a4-4fb2-4572-9b0e-e3254a5342b4.png">
