### ISSUE TITLE
Error: ETIMEDOUT

### ISSUE THREAD

**Issue by cyclops24** [chill117/proxy-lists#23]
Hi @chill117 
I got this error when try use your package within Meteor:

```
Error: ETIMEDOUT
W20160515-11:16:07.801(4.5)? (STDERR)     at [object Object]._onTimeout (/home/cy/Programming/Projects/proxyCheck/Sources/node_modules/proxy-lists/node_modules/request/request.js:762:15)
W20160515-11:16:07.801(4.5)? (STDERR)     at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```
It return many proxy but also return this error. This is my code:
```
Meteor.methods({
    proxyFetcher() {
        console.log("OK run");
        var options = {
            protocols: ['http'],
            anonymityLevels: ['elite'],
            sourcesBlackList: ['bitproxies', 'kingproxies']
        };

        var gettingProxies = ProxyLists.getProxies(options);
        Proxies.remove({});

        gettingProxies.on('data', Meteor.bindEnvironment(function(proxies) {
            console.log(proxies.length);
            proxies.forEach((proxy) => {
                Proxies.insert({proxy: proxy.ipAddress + ":" + proxy.port});
            });
            // Received some proxies.
        }));
    }
}
```

**Comment by chill117** [comment]
Try adding the following to your code to catch and print errors from the module:
```js
gettingProxies.on('error', function(error) {
    console.log(error);
});
```
This should give you the stack trace as well as the error message. I suspect that it is caused by one of the proxy list sources being unreachable from your machine at the time you are running the program.

**Comment by cyclops24** [comment]
Thanks man. It's worked. I add `on error` and all things fixed now.
