### ISSUE TITLE
I m getting following error in running proxy-lists CLI command

### ISSUE THREAD

**Issue by nishantsharmajecrc** [chill117/proxy-lists#28]
nishant@nishant-sjsu:~/workspacejs$ proxy-lists --help

module.js:340
    throw err;
          ^
Error: Cannot find module '.'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/proxy-lists/cli.js:10:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
nishant@nishant-sjsu:~/workspacejs$

**Comment by chill117** [comment]
@nishantsharmajecrc What version of node are you running?

**Comment by nishantsharmajecrc** [comment]
v0.10.25

**Comment by chill117** [comment]
That's a very old version. This module is only supporting node 4 or higher.

**Comment by nishantsharmajecrc** [comment]
I got it fixed. Added ./ in place of . and it fixed it

**Comment by th3l0b3** [comment]
add that to what?

**Comment by nishantsharmajecrc** [comment]
In cli.js of proxy-lists node module

**Comment by chill117** [comment]
Since more than one person has had this issue, I'll add the fix to the project and include it in the next release.
