### ISSUE TITLE
getProxies break for source "proxydb" 

### ISSUE THREAD

**Issue by jot-the-coder** [chill117/proxy-lists#42]
When invoking getProxies(), it always give the following:

```
Uncaught Error: Invalid option "countries": Object expected.
      at Object.module.exports.filterProxies (node_modules/proxy-lists/index.js:240:11)
      at EventEmitter.<anonymous> (node_modules/proxy-lists/index.js:157:26)
      at node_modules/proxy-lists/sources/proxydb.js:57:13
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2722:16
      at node_modules/proxy-lists/node_modules/async/dist/async.js:484:16
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2664:9
      at node_modules/proxy-lists/node_modules/async/dist/async.js:484:16
      at replenish (node_modules/proxy-lists/node_modules/async/dist/async.js:1025:25)
      at iterateeCallback (node_modules/proxy-lists/node_modules/async/dist/async.js:1015:17)
      at node_modules/proxy-lists/node_modules/async/dist/async.js:988:16
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2661:13
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2719:17
      at apply (node_modules/proxy-lists/node_modules/async/dist/async.js:41:25)
      at node_modules/proxy-lists/node_modules/async/dist/async.js:76:12
      at module.exports.parsePageHtml (node_modules/proxy-lists/sources/proxydb.js:137:3)
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2718:16
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2659:9
      at replenish (node_modules/proxy-lists/node_modules/async/dist/async.js:1030:17)
      at iterateeCallback (node_modules/proxy-lists/node_modules/async/dist/async.js:1015:17)
      at node_modules/proxy-lists/node_modules/async/dist/async.js:988:16
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2661:13
      at node_modules/proxy-lists/node_modules/async/dist/async.js:2719:17
      at apply (node_modules/proxy-lists/node_modules/async/dist/async.js:41:25)
      at node_modules/proxy-lists/node_modules/async/dist/async.js:76:12
      at Request._callback (node_modules/proxy-lists/sources/proxydb.js:104:4)
      at Request.self.callback (node_modules/proxy-lists/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/proxy-lists/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/proxy-lists/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)
```

After tracing, I found the following happened along with proxies data of "proxydb". So I find the following lines in "proxydb.js":
https://github.com/chill117/proxy-lists/blob/master/sources/proxydb.js#L33-L35

As "option.countries" expecting object, **is that underscore.js call "map" the cause of problem?** Say, using "_.mapObject" instead.
http://underscorejs.org/#mapObject

Thanks for your help. This project is a nice work!

**Comment by chill117** [comment]
This was an interesting one. I was able to reproduce the issue and have made a fix. It will be included in the next release.

**Comment by jot-the-coder** [comment]
@chill117 Thanks so much for your fix, your response is really fast! We can enjoy a happy holiday then... 😊
