### ISSUE TITLE
Gatherproxy: could not find download link

### ISSUE THREAD

**Issue by arfianadam** [chill117/proxy-lists#46]
How to reproduce:
- Just a fresh install and run the default cli command

Error code:
```
Error: Could not find download link.
    at Request._callback (/home/arfianadam/work/adam/web-bot/node_modules/proxy-lists/sources/gatherproxy.js:80:15)
    at Request.self.callback (/home/arfianadam/work/adam/web-bot/node_modules/proxy-lists/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/arfianadam/work/adam/web-bot/node_modules/proxy-lists/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/arfianadam/work/adam/web-bot/node_modules/proxy-lists/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```
any fix to this?
regardless, thank you for making this!

**Comment by chill117** [comment]
Looks like gatherproxy has changed the HTML of the page with the proxies download link. I can have a look in the next few days.

**Comment by arfianadam** [comment]
I've checked the code
```javascript
var $anchor = $('#body > p a').eq(0);
```
Gatherproxy's html in `http://www.gatherproxy.com/subscribe/infos`
```html
<div id="body" class="wrapper">
    <h1 class="page-title">You are logging as *********@yahoo.com</h1>
    <p>&nbsp;</p>
    <p>Expired date: 2/13/2018 9:02:02 AM</p>
    <p>&nbsp;</p>
    <p>
        <a href="/proxylist/downloadproxylist/?sid=*******">Download fully 10011 proxies</a>
        (Last checked past 24 hours - The list is updated continuously per second)
    </p>
    <p>&nbsp;</p>
    ...
</div>
```
It should return the url correctly. I think it is related to something else?

**Comment by chill117** [comment]
Thank you for taking the time to research this. I have fixed the issue with [this commit](https://github.com/chill117/proxy-lists/commit/aa87cd6f4865e0e960ce573907454c427d0ec2ec). The issue was a redirect to www.gatherproxy.com during the login attempt.
