### ISSUE TITLE
Error: connect ECONNREFUSED 112.215.37.181:443

### ISSUE THREAD

**Issue by arfianadam** [chill117/proxy-lists#47]
How to reproduce:
- Just a fresh install and run the default cli command

Error code:
```
{ Error: connect ECONNREFUSED 112.215.37.181:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '112.215.37.181',
  port: 443 }
```
any thoughts? thanks!

**Comment by chill117** [comment]
I don't know what that IP address is, but maybe this is related to maxiproxies no longer working (it redirects to dreamproxies.com now).
