### ISSUE TITLE
ipType Error

### ISSUE THREAD

**Issue by Raslin777** [chill117/proxy-lists#75]
Looks like it has a problem getting the ipType

```
C:\Users\wmarino\Desktop\ProxyList>proxy-lists -V
1.14.1

C:\Users\wmarino\Desktop\ProxyList>proxy-lists getProxies
Getting proxies...
Error: Missing required option (`option.bitproxies.apiKey`): You can get an API key for this service by creating an account at https://bitproxies.eu/
Error: Missing required option (`option.kingproxies.apiKey`): You can get an API key for this service by creating an account at https://kingproxies.com/register
Writing output to C:\Users\wmarino\Desktop\ProxyList/proxies.txt
C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\geoip-native-lite\index.js:33
                        throw new Error('Data (' + ipType + ') has not been loaded.');
                        ^

Error: Data (ipv6) has not been loaded.
    at Object.lookup (C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\geoip-native-lite\index.js:33:10)
    at C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\index.js:180:38
    at Function._.map._.collect (C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\underscore\underscore.js:172:24)
    at EventEmitter.<anonymous> (C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\index.js:178:17)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\sources\freeproxylist.js:36:14
    at C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\async\dist\async.js:2556:16
    at C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\async\dist\async.js:421:16
    at C:\Users\wmarino\AppData\Roaming\npm\node_modules\proxy-lists\node_modules\async\dist\async.js:2494:9

```

**Comment by Raslin777** [comment]
This seems to temp fix the issue:
proxy-lists getProxies  --ip-types ipv4,ipv6

**Comment by lolgans** [comment]
You can also set it directly in the options object:
`
const proxyOptions: Options = {
    ipTypes: ['ipv4']
};
`

**Comment by chill117** [comment]
This has been fixed in the latest version.
