### ISSUE TITLE
Problem with proxies24 source

### ISSUE THREAD

**Issue by parsibox** [chill117/proxy-lists#77]
hi
when i run example at end of output say this error :

```
Error: Could not find hosts HTML element.
    at Object.parseListPageHtml (/var/www/node/node_modules/proxy-lists/sources/proxies24.js:203:15)
    at /var/www/node/node_modules/async/dist/async.js:2550:16
    at /var/www/node/node_modules/async/dist/async.js:2489:9
    at replenish (/var/www/node/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/var/www/node/node_modules/async/dist/async.js:931:17)
    at /var/www/node/node_modules/async/dist/async.js:906:16
    at /var/www/node/node_modules/async/dist/async.js:2491:13
    at /var/www/node/node_modules/async/dist/async.js:2552:17
    at Request._callback (/var/www/node/node_modules/proxy-lists/sources/proxies24.js:175:4)
    at Request.self.callback (/var/www/node/node_modules/request/request.js:188:22)


```

my node version is 
```
 node -v
v8.11.2
```
on centos 7 64 bit

**Comment by parsibox** [comment]
```
Error: Missing required option (`option.bitproxies.apiKey`): You can get an API key for this service by creating an account at https://bitproxies.eu/
Error: Missing required option (`option.kingproxies.apiKey`): You can get an API key for this service by creating an account at https://kingproxies.com/register
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }

```

**Comment by thorncorona** [comment]
You don't have the right certificates installed. See: https://www.npmjs.com/package/ssl-root-cas for possible solutions

**Comment by chill117** [comment]
Appears to be working now.
