### ISSUE TITLE
Error: [proxydb] waiting for selector "table tbody tr" failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by marcpre** [chill117/proxy-lists#93]
Hello,

I am using `"proxy-lists": "^1.16.0",` with `node v10.15.3` and when executing:

```
async function main() {

    const options = {
        countries: null
    };

    // `gettingProxies` is an event emitter object.
    const gettingProxies = ProxyLists.getProxies(options);

    gettingProxies.on('data', function (proxies) {
        console.log(proxies);
        // Received some proxies.
    });

    gettingProxies.on('error', function (error) {
        // Some error has occurred.
        console.error(error);
    });

    gettingProxies.once('end', function () {
        // Done getting proxies.
    });

    // request from this IP: http://pubproxy.com/api/proxy

}

main()

```

I am getting the following error:

```
Error: [proxydb] waiting for selector "table tbody tr" failed: timeout 30000ms exceeded
    at new WaitTask (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:840:28)
    at Frame._waitForSelectorOrXPath (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:731:12)
    at Frame.waitForSelector (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:690:17)
    at Frame.waitFor (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:675:19)
    at Page.waitFor (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\Page.js:999:29)
    at Object.waitForListElement (C:\project\node_modules\data-sourcer\abstracts\scraper-paginated-list.js:145:8)
    at C:\project\node_modules\async\dist\async.js:2577:16
    at C:\project\node_modules\async\dist\async.js:2516:9
    at replenish (C:\project\node_modules\async\dist\async.js:1011:17)
    at iterateeCallback (C:\project\node_modules\async\dist\async.js:995:17)
    at C:\project\node_modules\async\dist\async.js:969:16
    at C:\project\node_modules\async\dist\async.js:2518:13
    at C:\project\node_modules\async\dist\async.js:2579:17
    at C:\project\node_modules\data-sourcer\abstracts\scraper-paginated-list.js:117:4
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: [sockslist] waiting for selector ".proxytbl tbody tr:not(:first-child)" failed: timeout 30000ms exceeded
    at new WaitTask (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:840:28)
    at Frame._waitForSelectorOrXPath (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:731:12)
    at Frame.waitForSelector (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:690:17)
    at Frame.waitFor (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\FrameManager.js:675:19)
    at Page.waitFor (C:\project\node_modules\data-sourcer\node_modules\puppeteer\lib\Page.js:999:29)
    at Object.waitForListElement (C:\project\node_modules\data-sourcer\abstracts\scraper-paginated-list.js:145:8)
    at C:\project\node_modules\async\dist\async.js:2577:16
    at C:\project\node_modules\async\dist\async.js:2516:9
    at replenish (C:\project\node_modules\async\dist\async.js:1011:17)
    at iterateeCallback (C:\project\node_modules\async\dist\async.js:995:17)
    at C:\project\node_modules\async\dist\async.js:969:16
    at C:\project\node_modules\async\dist\async.js:2518:13
    at C:\project\node_modules\async\dist\async.js:2579:17
    at C:\project\node_modules\data-sourcer\abstracts\scraper-paginated-list.js:139:4
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Any suggestion what i am doing wrong?

I appreciate your reply!

**Comment by chill117** [comment]
From time to time the sources break because the web resources change their structure. See #91 for a full list of broken and fixed sources.
